Bivariate branch
cmudig/AutoProfiler pull request #113
Opened 2023-02-13 16:17 UTC by yuqizhang99

## Functionality

Create bivariate chart components for Q+C Q+T

## Issues addressed

#95

2023-04-05 19:24 UTC, yuqizhang99 commented
The current branch is up to date except for the Q+T bivariate chart

2023-04-20 15:59 UTC, willeppy requested changes
# Design
Plus button for add chart
- [x] Move to bottom right hand side
- [ ] Maybe make wider (not super important)
- [x] Make sure that the hover only happens on the actual button, not the whole div row
- [x] Should always be below newly added charts!!!

Column drop downs
- [ ] add left padding so not so tight
- [ ] drop down should disappear when you click outside
- [ ] Is it possible to make the seach stay inline rather than at the top? Like [this example](https://www.w3schools.com/howto/howto_js_filter_dropdown.asp)
- [ ] OR just use a normal dropdown and we can worry about searchability later (my vote!)
- [ ] Can you add icon for the column data type in the dropdown?

Added chart tab
- [ ] Make the same width, height, and color as normal column button
- [ ] Icon is cluttered
- [ ] Change aggregation selection to be normal dropdown (Look at the one for Sort by at the top)
- [x] What does "---" mean in axis?

Bar chart
- [ ] Make y axis wider so can more easily read values
- [ ] Is it possible to show a tooltip on hover for each bar with the x and y axis values?
- [ ] Sort y axis by default as descending
- [ ] add sorting for y axis

Time chart
- [ ] Changing time agg to second, minute, hour overplots on x axis like crazy
- [ ] Make dropdowns normal selects here as well (like sort by)

For charts tab
- [ ] Change delete to trash can icon

# Authoring Flow
- [ ] When I hit add to chart, the plus button should disappear until I have hit done or cancel; OR change the plus button to say "cancel" once it is clicked (I vote for disappear though)
- [ ] Do not allow adding same chart twice: right now, I can add same chart twice (county + year, year + county)
- [ ] Add some feedback text for what is being filtered in selectors. E.g. if I first select a Q column, it should say "Only showing nominal columns" in second dropdown. This might not be necessary if include data types in dropdown though
- [ ] done should be disabled until I have selected both dropdowns
- [ ] Disable second dropdown until first is selected

# Testing
- [ ] Be sure to test edge cases like if dataframe is completley empty (freezes up right now)
- [ ] Test that it works if one (or both) of the columns is all null 
- [ ] BUG: If first selected column is Q then cant select second dropdown

2023-04-20 15:59 UTC, willeppy commented on .github/pull_request_template.md
Remove this file from PR

2023-04-20 15:59 UTC, willeppy commented on .github/screenshots/profiler_sc.png
Remove from PR

2023-04-20 15:59 UTC, willeppy commented on examples/SF Housing Demo.ipynb
Remove from PR

2023-05-07 10:40 UTC, yuqizhang99 commented
Some bugs required to fix:
- [ ] After clicking "Add" button, there should be an option for users to cancel this interaction
- [ ] The dropdown menu should have limited width

2023-05-19 04:19 UTC, yuqizhang99 commented
Sorry I force-pushed the code because I squashed the commits to the commit behind the remote.

2023-06-14 17:58 UTC, willeppy commented
Final TODOs
- [ ] Change done button to be done or cancel
- [ ] add button for delete
- [ ] make edit button look nicer
- [ ] clean up code

2023-06-14 21:24 UTC, willeppy approved these changes

2023-06-14 21:25 UTC, merged